// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQgnVBXXDakUiWsniGtyAKi04kz8T9PBs',
    appId: '1:980308178135:web:80717366e2257df23bac92',
    messagingSenderId: '980308178135',
    projectId: 'fir-test-cafc7',
    authDomain: 'fir-test-cafc7.firebaseapp.com',
    storageBucket: 'fir-test-cafc7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAcL3PnGaCPOvN5gj7ttI6WL9Vst1f6-0',
    appId: '1:980308178135:android:c4d06ce357fffdbd3bac92',
    messagingSenderId: '980308178135',
    projectId: 'fir-test-cafc7',
    storageBucket: 'fir-test-cafc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlBc3pMYx7JcK1MxNNTS4T3DBau9DugMw',
    appId: '1:980308178135:ios:3c3fe3767720d7283bac92',
    messagingSenderId: '980308178135',
    projectId: 'fir-test-cafc7',
    storageBucket: 'fir-test-cafc7.appspot.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlBc3pMYx7JcK1MxNNTS4T3DBau9DugMw',
    appId: '1:980308178135:ios:daa8d4399e125b953bac92',
    messagingSenderId: '980308178135',
    projectId: 'fir-test-cafc7',
    storageBucket: 'fir-test-cafc7.appspot.com',
    iosBundleId: 'com.example.firebaseTest.RunnerTests',
  );
}
